name: Python Application CI

on:
  push:
    branches:
      - main-d17
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting with pylint
        env:
          PYTHONPATH: ${{  github.workspace  }}/src
        run: |
          pylint --disable=C0114,C0115,C0116,C0103,W0611,R0913,R0917,R0903,W0104,R1710 src/
          
      - name: Set PYTHONPATH for testing
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest -s