name: Python Application CI

on:
  push:
    branches:
      - test-branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting with pylint
        run: |
          pylint src/
  
      - name: Run linting with flake8
        run: |
          flake8 src/

      - name: Run tests
        run: |
          pytest